import Head from 'next/head';

export default function HeadMeta(props){
    return (<Head>
    <meta httpEquiv="content-type" content="text/html;charset=UTF-8" />
    {/* /Added by HTTrack */}
    <meta charSet="UTF-8" />
    <title>{props.page_title? props.page_title : "Aydinty Social Community"}</title>
    <meta name="robots" content="max-image-preview:large" />
    <link rel="dns-prefetch" href="http://fonts.googleapis.com/" />
    <link rel="dns-prefetch" href="http://s.w.org/" />
    <link
      rel="alternate"
      type="application/rss+xml"
      title="Vikinger » Feed"
      href="feed/index.html"
    />
    <link
      rel="alternate"
      type="application/rss+xml"
      title="Vikinger » Comments Feed"
      href="comments/feed/index.html"
    />
    <style
      type="text/css"
      dangerouslySetInnerHTML={{
        __html:
          "\nimg.wp-smiley,\nimg.emoji {\n\tdisplay: inline !important;\n\tborder: none !important;\n\tbox-shadow: none !important;\n\theight: 1em !important;\n\twidth: 1em !important;\n\tmargin: 0 .07em !important;\n\tvertical-align: -0.1em !important;\n\tbackground: none !important;\n\tpadding: 0 !important;\n}\n"
      }}
    />
    <link
      rel="stylesheet"
      id="dashicons-css"
      href="/theme/wp-includes/css/dashicons.min080f.css?ver=5.8.2"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-verified-member-css"
      href="/theme/wp-content/plugins/bp-verified-member/assets/css/style9632.css?ver=1.2.3"
      type="text/css"
      media="all"
    />
    <style
      id="bp-verified-member-inline-css"
      type="text/css"
      dangerouslySetInnerHTML={{
        __html:
          "\n\n\t\t\t:root {\n\t\t\t\t--bp-verified-members-verified-badge-shape: url('/theme/wp-content/plugins/bp-verified-member/assets/images/mask-circle.svg');\n\t\t\t\t--bp-verified-members-unverified-badge-shape: url('/theme/wp-content/plugins/bp-verified-member/assets/images/mask-circle.svg');\n\t\t\t}\n\t\t\n\t\t\t.bp-verified-badge,\n\t\t\t.bp-verified-member .member-name-item > a:after,\n\t\t\t.bp-verified-member .item-title > a:after,\n\t\t\t.bp-verified-member > .author > a:after,\n\t\t\t.bp-verified-member .member-name > a:after {\n\t\t\t\tbackground-color: #1DA1F2 !important;\n\t\t\t}\n\t\t\t\n\t\t\t.bp-unverified-badge,\n\t\t\t.bp-unverified-member .member-name-item > a:after,\n\t\t\t.bp-unverified-member .item-title > a:after,\n\t\t\t.bp-unverified-member > .author > a:after,\n\t\t\t.bp-unverified-member .member-name > a:after {\n\t\t\t\tbackground-color: #DD9933 !important;\n\t\t\t}\n\t\t\n"
      }}
    />
    <link
      rel="stylesheet"
      id="wp-block-library-css"
      href="/theme/wp-includes/css/dist/block-library/style.min080f.css?ver=5.8.2"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-login-form-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-core/css/blocks/login-form.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-member-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-members/css/blocks/member.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-members-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-members/css/blocks/members.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-dynamic-members-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-members/css/blocks/dynamic-members.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-latest-activities-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-activity/css/blocks/latest-activities.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-friends-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-friends/css/blocks/friends.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-group-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-groups/css/blocks/group.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-groups-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-groups/css/blocks/groups.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-dynamic-groups-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-groups/css/blocks/dynamic-groups.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bp-sitewide-notices-block-css"
      href="/theme/wp-content/plugins/buddypress/bp-messages/css/blocks/sitewide-notices.mineba3.css?ver=9.1.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wc-blocks-vendors-style-css"
      href="/theme/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-vendors-style5c45.css?ver=6.3.3"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wc-blocks-style-css"
      href="/theme/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-style5c45.css?ver=6.3.3"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="bbp-default-css"
      href="/theme/wp-content/plugins/bbpress/templates/default/css/bbpress.mina19e.css?ver=2.6.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="pmpro_frontend-css"
      href="/theme/wp-content/plugins/paid-memberships-pro/css/frontendd7ad.css?ver=2.6.6"
      type="text/css"
      media="screen"
    />
    <link
      rel="stylesheet"
      id="pmpro_print-css"
      href="/theme/wp-content/plugins/paid-memberships-pro/css/printd7ad.css?ver=2.6.6"
      type="text/css"
      media="print"
    />
    <link
      rel="stylesheet"
      id="woocommerce-layout-css"
      href="/theme/wp-content/plugins/woocommerce/assets/css/woocommerce-layoutaf8e.css?ver=6.0.0"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="woocommerce-smallscreen-css"
      href="/theme/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreenaf8e.css?ver=6.0.0"
      type="text/css"
      media="only screen and (max-width: 768px)"
    />
    <link
      rel="stylesheet"
      id="woocommerce-general-css"
      href="/theme/wp-content/plugins/woocommerce/assets/css/woocommerceaf8e.css?ver=6.0.0"
      type="text/css"
      media="all"
    />
    <style
      id="woocommerce-inline-inline-css"
      type="text/css"
      dangerouslySetInnerHTML={{
        __html:
          "\n.woocommerce form .form-row .required { visibility: visible; }\n"
      }}
    />
    <link
      rel="stylesheet"
      id="vikinger-fonts-css"
      href="https://fonts.googleapis.com/css?family=Rajdhani%3A400%2C500%2C600%2C700%7CTitillium+Web%3A400%2C900&display=swap&ver=5.8.2"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="vikinger-simplebar-styles-css"
      href="/theme/wp-content/themes/vikinger/css/vendor/simplebar8a54.css?ver=1.0.0"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="vikinger-swiper-slider-styles-css"
      href="/theme/wp-content/themes/vikinger/css/vendor/swiper.min8a54.css?ver=1.0.0"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="vikinger-styles-css"
      href="/theme/wp-content/themes/vikinger/style9086.css?ver=3.9.0"
      type="text/css"
      media="all"
    />
    <style
      id="vikinger-styles-inline-css"
      type="text/css"
      dangerouslySetInnerHTML={{
        __html:
          "\n\n    :root {\n      --font-primary: Rajdhani, sans-serif;\n      --font-secondary: Titillium Web, sans-serif;\n    }\n  \n:root { --color-wplogin-body: #fff;--color-wplogin-header-text: #fff;--color-header-background: #615dfa;--color-header-logo-background: #00c7d9;--color-header-text: #fff;--color-header-icon: #8b88ff;--color-header-icon-hover: #fff;--color-header-profile-settings-icon: #fff;--color-header-mobilemenu-trigger-icon: #fff;--color-header-divider: #7a77fd;--color-header-input-background: #4e4ac8;--color-header-input-placeholder: #8b88ff;--color-header-progressbar-line-gradient-start: #41efff;--color-header-progressbar-line-gradient-end: #41efff;--color-header-progressbar-underline: #4a46c8;--color-body: #f8f8fb;--color-box-background: #fff;--color-box-background-alt: #fcfcfd;--color-box-over-box-background: #fff;--color-box-over-box-light-background: #fff;--color-box-highlight-background: #f7f7fb;--color-box-hover-background: #f2f2f9;--color-box-shadow: 0 0 40px 0 rgba(94,92,154, .06);--color-overbox-shadow: 3px 5px 20px 0 rgba(94,92,154, .12);--color-overbox-dark-shadow: 0 0 40px 0 rgba(94,92,154, .12);--color-overbox-big-shadow: 3px 5px 40px 0 rgba(94,92,154, .1);--color-text: #3e3f5e;--color-text-alt: #8f91ac;--color-text-alt-2: #adafca;--color-icon: #adafca;--color-icon-highlighted: #3e3f5e;--color-border: #dedeea;--color-divider: #eaeaf5;--color-progressbar-line-gradient-start: #615dfa;--color-progressbar-line-gradient-end: #41efff;--color-progressbar-underline: #e7e8ee;--color-avatar-rank-hexagon: #45437f;--color-primary: #23d2e2;--color-primary-hover: #1bc5d4;--color-primary-light: #41efff;--color-primary-dark: #00c7d9;--color-primary-shadow: 4px 7px 12px 0 rgba(35,210,226, .2);--color-secondary: #615dfa;--color-secondary-hover: #5753e4;--color-secondary-dark: #45437f;--color-secondary-shadow: 4px 7px 12px 0 rgba(97,93,250, .2);--color-tertiary: #fd4350;--color-tertiary-hover: #dd343f;--color-tertiary-shadow: 4px 7px 12px 0 rgba(253,67,80, .2);--color-loading-screen-background: #3e3f5e;--color-loading-bar-1: #615dfa;--color-loading-bar-2: #5d71fb;--color-loading-bar-3: #5983fb;--color-loading-bar-4: #549afc;--color-loading-bar-5: #4eb2fd;--color-loading-bar-6: #49c9fe;--color-loading-bar-7: #45ddfe;--color-loading-bar-8: #41efff;--color-overlay: rgba(21,21,31, .96);;--color-notice-overlay-background-primary: rgba(35,210,226, .14);--color-notice-overlay-background-secondary: rgba(97,93,250, .14);--color-notice-overlay-background-tertiary: rgba(253,67,80, .14);--color-avatar-overlay-background: rgba(97,93,250, .9);--footer-navigation-display-mobile: none; }\n"
      }}
    />
    <link
      rel="stylesheet"
      id="elementor-icons-css"
      href="/theme/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min05c8.css?ver=5.13.0"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-frontend-legacy-css"
      href="/theme/wp-content/plugins/elementor/assets/css/frontend-legacy.min9d52.css?ver=3.5.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-frontend-css"
      href="/theme/wp-content/plugins/elementor/assets/css/frontend.min9d52.css?ver=3.5.1"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-post-875-css"
      href="/theme/wp-content/uploads/elementor/css/post-875438c.css?ver=1640009854"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-global-css"
      href="/theme/wp-content/uploads/elementor/css/global438c.css?ver=1640009854"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-post-876-css"
      href="/theme/wp-content/uploads/elementor/css/post-8760dce.css?ver=1640009855"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="google-fonts-1-css"
      href="https://fonts.googleapis.com/css?family=Rajdhani%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CTitillium+Web%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&display=auto&ver=5.8.2"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-icons-shared-0-css"
      href="/theme/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min52d5.css?ver=5.15.3"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-icons-fa-solid-css"
      href="/theme/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min52d5.css?ver=5.15.3"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-icons-fa-regular-css"
      href="/theme/wp-content/plugins/elementor/assets/lib/font-awesome/css/regular.min52d5.css?ver=5.15.3"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="elementor-icons-fa-brands-css"
      href="/theme/wp-content/plugins/elementor/assets/lib/font-awesome/css/brands.min52d5.css?ver=5.15.3"
      type="text/css"
      media="all"
    />
    <link rel="https://api.w.org/" href="/theme/wp-json/index.html" />
    <link
      rel="alternate"
      type="application/json"
      href="/theme/wp-json/wp/v2/pages/876.json"
    />
    <link
      rel="EditURI"
      type="application/rsd+xml"
      title="RSD"
      href="xmlrpc0db0.php?rsd"
    />
    <link
      rel="wlwmanifest"
      type="application/wlwmanifest+xml"
      href="/theme/wp-includes/wlwmanifest.xml"
    />
    <meta name="generator" content="WordPress 5.8.2" />
    <meta name="generator" content="WooCommerce 6.0.0" />
    <link rel="canonical" href="index.html" />
    <link rel="shortlink" href="index.html" />
    <link
      rel="alternate"
      type="application/json+oembed"
      href="/theme/wp-json/oembed/1.0/embedfdfa.json?url=https%3A%2F%2Fodindesignthemes.com%2Fvikinger-theme%2F"
    />
    <link
      rel="alternate"
      type="text/xml+oembed"
      href="/theme/wp-json/oembed/1.0/embed90b4?url=https%3A%2F%2Fodindesignthemes.com%2Fvikinger-theme%2F&format=xml"
    />
    <noscript>
      &lt;style&gt;.woocommerce-product-gallery{"{"} opacity: 1 !important; {"}"}
      &lt;/style&gt;
    </noscript>
    <link
      rel="icon"
      href="/theme/wp-content/uploads/2020/09/vkfooterlogo.png"
      sizes="32x32"
    />
    <link
      rel="icon"
      href="/theme/wp-content/uploads/2020/09/vkfooterlogo.png"
      sizes="192x192"
    />
    <link
      rel="apple-touch-icon"
      href="/theme/wp-content/uploads/2020/09/vkfooterlogo.png"
    />
    <meta
      name="msapplication-TileImage"
      content="https://odindesignthemes.com/vikinger-theme//theme/wp-content/uploads/2020/09/vkfooterlogo.png"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, viewport-fit=cover"
    />
  </Head>);
}